package container

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
)

func TestDefaultComposeOptions(t *testing.T) {
	opts := DefaultComposeOptions("/path/to/bench")

	if opts.BenchPath != "/path/to/bench" {
		t.Errorf("expected BenchPath '/path/to/bench', got %s", opts.BenchPath)
	}
	if opts.Mode != "dev" {
		t.Errorf("expected Mode 'dev', got %s", opts.Mode)
	}
	if opts.WebPort != 8000 {
		t.Errorf("expected WebPort 8000, got %d", opts.WebPort)
	}
	if opts.SocketPort != 9000 {
		t.Errorf("expected SocketPort 9000, got %d", opts.SocketPort)
	}
	if opts.DBPort != 3306 {
		t.Errorf("expected DBPort 3306, got %d", opts.DBPort)
	}
	if opts.Database != "mariadb" {
		t.Errorf("expected Database 'mariadb', got %s", opts.Database)
	}
	if !opts.IncludeDB {
		t.Error("expected IncludeDB to be true")
	}
	if !opts.IncludeRedis {
		t.Error("expected IncludeRedis to be true")
	}
	if !opts.Volumes {
		t.Error("expected Volumes to be true")
	}
}

func TestComposeOptionsStruct(t *testing.T) {
	opts := ComposeOptions{
		BenchPath:    "/my/bench",
		ProjectName:  "myproject",
		AppName:      "myapp",
		ImageTag:     "myapp:v1.0",
		Mode:         "prod",
		WebPort:      8080,
		SocketPort:   9090,
		DBPort:       3307,
		Database:     "postgres",
		IncludeDB:    true,
		IncludeRedis: false,
		Volumes:      true,
	}

	if opts.ProjectName != "myproject" {
		t.Errorf("unexpected ProjectName: %s", opts.ProjectName)
	}
	if opts.Database != "postgres" {
		t.Errorf("unexpected Database: %s", opts.Database)
	}
}

func TestGenerateDockerComposeDevMode(t *testing.T) {
	opts := ComposeOptions{
		BenchPath:    "/bench",
		AppName:      "testapp",
		Mode:         "dev",
		WebPort:      8000,
		SocketPort:   9000,
		DBPort:       3306,
		Database:     "mariadb",
		IncludeDB:    true,
		IncludeRedis: true,
		Volumes:      true,
	}

	result := GenerateDockerCompose(opts)

	// Check header
	if !strings.Contains(result, "Generated by weg") {
		t.Error("expected header comment")
	}
	if !strings.Contains(result, "Mode: dev") {
		t.Error("expected dev mode in header")
	}

	// Check services
	if !strings.Contains(result, "web:") {
		t.Error("expected web service")
	}
	if !strings.Contains(result, "worker:") {
		t.Error("expected worker service")
	}
	if !strings.Contains(result, "scheduler:") {
		t.Error("expected scheduler service")
	}
	if !strings.Contains(result, "socketio:") {
		t.Error("expected socketio service")
	}
	if !strings.Contains(result, "db:") {
		t.Error("expected db service")
	}
	if !strings.Contains(result, "redis-cache:") {
		t.Error("expected redis-cache service")
	}
	if !strings.Contains(result, "redis-queue:") {
		t.Error("expected redis-queue service")
	}

	// Check dev mode volumes
	if !strings.Contains(result, "./apps:/home/frappe/frappe-bench/apps") {
		t.Error("expected dev mode app volume mount")
	}

	// Check MariaDB
	if !strings.Contains(result, "mariadb:10.6") {
		t.Error("expected mariadb image")
	}
}

func TestGenerateDockerComposeProdMode(t *testing.T) {
	opts := ComposeOptions{
		BenchPath:    "/bench",
		AppName:      "prodapp",
		Mode:         "prod",
		WebPort:      80,
		SocketPort:   9000,
		DBPort:       3306,
		Database:     "mariadb",
		IncludeDB:    true,
		IncludeRedis: true,
		Volumes:      true,
	}

	result := GenerateDockerCompose(opts)

	// Check prod mode
	if !strings.Contains(result, "Mode: prod") {
		t.Error("expected prod mode in header")
	}

	// Check named volumes for prod
	if !strings.Contains(result, "sites-data:") {
		t.Error("expected sites-data volume")
	}
	if !strings.Contains(result, "db-data:") {
		t.Error("expected db-data volume")
	}
}

func TestGenerateDockerComposePostgres(t *testing.T) {
	opts := ComposeOptions{
		BenchPath:    "/bench",
		AppName:      "pgapp",
		Mode:         "dev",
		WebPort:      8000,
		SocketPort:   9000,
		DBPort:       5432,
		Database:     "postgres",
		IncludeDB:    true,
		IncludeRedis: true,
		Volumes:      false,
	}

	result := GenerateDockerCompose(opts)

	// Check PostgreSQL
	if !strings.Contains(result, "postgres:15") {
		t.Error("expected postgres image")
	}
	if !strings.Contains(result, "POSTGRES_USER") {
		t.Error("expected postgres env vars")
	}
	if !strings.Contains(result, "5432:5432") {
		t.Error("expected postgres port mapping")
	}
}

func TestGenerateDockerComposeNoRedis(t *testing.T) {
	opts := ComposeOptions{
		BenchPath:    "/bench",
		AppName:      "noredis",
		Mode:         "dev",
		WebPort:      8000,
		SocketPort:   9000,
		IncludeDB:    true,
		IncludeRedis: false,
	}

	result := GenerateDockerCompose(opts)

	if strings.Contains(result, "redis-cache:") {
		t.Error("should not include redis-cache service")
	}
	if strings.Contains(result, "redis-queue:") {
		t.Error("should not include redis-queue service")
	}
}

func TestGenerateDockerComposeNoDB(t *testing.T) {
	opts := ComposeOptions{
		BenchPath:    "/bench",
		AppName:      "nodb",
		Mode:         "dev",
		WebPort:      8000,
		SocketPort:   9000,
		IncludeDB:    false,
		IncludeRedis: true,
	}

	result := GenerateDockerCompose(opts)

	// Should not have db: service
	lines := strings.Split(result, "\n")
	for i, line := range lines {
		if strings.TrimSpace(line) == "db:" {
			// Check if this is a service definition (indented at service level)
			if i > 0 && strings.HasPrefix(lines[i], "  db:") {
				t.Error("should not include db service")
			}
		}
	}
}

func TestGenerateDockerComposeCustomImageTag(t *testing.T) {
	opts := ComposeOptions{
		BenchPath:    "/bench",
		AppName:      "myapp",
		ImageTag:     "ghcr.io/myorg/myapp:v2.0.0",
		Mode:         "dev",
		WebPort:      8000,
		SocketPort:   9000,
		IncludeDB:    false,
		IncludeRedis: false,
	}

	result := GenerateDockerCompose(opts)

	if !strings.Contains(result, "ghcr.io/myorg/myapp:v2.0.0") {
		t.Error("expected custom image tag")
	}
}

func TestGenerateDockerComposeDefaultImageTag(t *testing.T) {
	opts := ComposeOptions{
		BenchPath:    "/bench",
		AppName:      "myapp",
		Mode:         "dev",
		WebPort:      8000,
		SocketPort:   9000,
		IncludeDB:    false,
		IncludeRedis: false,
	}

	result := GenerateDockerCompose(opts)

	if !strings.Contains(result, "myapp:latest") {
		t.Error("expected default image tag myapp:latest")
	}
}

func TestGenerateDockerComposeProjectName(t *testing.T) {
	opts := ComposeOptions{
		BenchPath:   "/path/to/my-bench",
		ProjectName: "custom-project",
		AppName:     "app",
		Mode:        "dev",
		WebPort:     8000,
		SocketPort:  9000,
	}

	result := GenerateDockerCompose(opts)

	if !strings.Contains(result, "custom-project") {
		t.Error("expected custom project name in header")
	}
}

func TestWriteDockerCompose(t *testing.T) {
	tmpDir := t.TempDir()

	content := "version: '3.8'\nservices:\n  web:\n    image: test\n"
	err := WriteDockerCompose(tmpDir, content)
	if err != nil {
		t.Fatalf("failed to write docker-compose: %v", err)
	}

	// Read it back
	data, err := os.ReadFile(filepath.Join(tmpDir, "docker-compose.yml"))
	if err != nil {
		t.Fatalf("failed to read docker-compose: %v", err)
	}

	if string(data) != content {
		t.Errorf("content mismatch: got %s", string(data))
	}
}

func TestGenerateDockerComposePortMappings(t *testing.T) {
	opts := ComposeOptions{
		BenchPath:    "/bench",
		AppName:      "app",
		Mode:         "dev",
		WebPort:      8080,
		SocketPort:   9090,
		DBPort:       3307,
		Database:     "mariadb",
		IncludeDB:    true,
		IncludeRedis: false,
	}

	result := GenerateDockerCompose(opts)

	if !strings.Contains(result, "8080:8000") {
		t.Error("expected web port mapping 8080:8000")
	}
	if !strings.Contains(result, "9090:9000") {
		t.Error("expected socketio port mapping 9090:9000")
	}
	if !strings.Contains(result, "3307:3306") {
		t.Error("expected db port mapping 3307:3306")
	}
}
