package container

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// ComposeOptions configures Docker Compose generation
type ComposeOptions struct {
	BenchPath    string
	ProjectName  string
	AppName      string
	ImageTag     string
	Mode         string // dev, prod
	WebPort      int
	SocketPort   int
	DBPort       int
	Database     string // mariadb, postgres
	IncludeDB    bool
	IncludeRedis bool
	Volumes      bool // Use volumes for persistence
}

// DefaultComposeOptions returns sensible defaults
func DefaultComposeOptions(benchPath string) ComposeOptions {
	return ComposeOptions{
		BenchPath:    benchPath,
		Mode:         "dev",
		WebPort:      8000,
		SocketPort:   9000,
		DBPort:       3306,
		Database:     "mariadb",
		IncludeDB:    true,
		IncludeRedis: true,
		Volumes:      true,
	}
}

// GenerateDockerCompose creates a docker-compose.yml for the bench
func GenerateDockerCompose(opts ComposeOptions) string {
	projectName := opts.ProjectName
	if projectName == "" {
		projectName = filepath.Base(opts.BenchPath)
	}

	imageTag := opts.ImageTag
	if imageTag == "" {
		imageTag = fmt.Sprintf("%s:latest", opts.AppName)
	}

	var compose strings.Builder

	// Header
	compose.WriteString(fmt.Sprintf(`# Generated by weg - Docker Compose for %s
# Mode: %s

version: "3.8"

services:
`, projectName, opts.Mode))

	// Web service
	compose.WriteString(fmt.Sprintf(`  web:
    image: %s
    build:
      context: .
      target: web
    ports:
      - "%d:8000"
    environment:
      - FRAPPE_SITE_NAME=%s.localhost
    depends_on:
`, imageTag, opts.WebPort, opts.AppName))

	if opts.IncludeDB {
		compose.WriteString("      - db\n")
	}
	if opts.IncludeRedis {
		compose.WriteString("      - redis-cache\n")
		compose.WriteString("      - redis-queue\n")
	}

	if opts.Mode == "dev" {
		compose.WriteString(`    volumes:
      - ./apps:/home/frappe/frappe-bench/apps:cached
      - ./sites:/home/frappe/frappe-bench/sites:cached
`)
	} else if opts.Volumes {
		compose.WriteString(`    volumes:
      - sites-data:/home/frappe/frappe-bench/sites
`)
	}

	compose.WriteString(`    restart: unless-stopped

`)

	// Worker service
	compose.WriteString(fmt.Sprintf(`  worker:
    image: %s
    build:
      context: .
      target: worker
    environment:
      - FRAPPE_SITE_NAME=%s.localhost
    depends_on:
      - web
`, imageTag, opts.AppName))

	if opts.Mode == "dev" {
		compose.WriteString(`    volumes:
      - ./apps:/home/frappe/frappe-bench/apps:cached
      - ./sites:/home/frappe/frappe-bench/sites:cached
`)
	} else if opts.Volumes {
		compose.WriteString(`    volumes:
      - sites-data:/home/frappe/frappe-bench/sites
`)
	}

	compose.WriteString(`    restart: unless-stopped

`)

	// Scheduler service
	compose.WriteString(fmt.Sprintf(`  scheduler:
    image: %s
    build:
      context: .
      target: scheduler
    environment:
      - FRAPPE_SITE_NAME=%s.localhost
    depends_on:
      - web
`, imageTag, opts.AppName))

	if opts.Mode == "dev" {
		compose.WriteString(`    volumes:
      - ./apps:/home/frappe/frappe-bench/apps:cached
      - ./sites:/home/frappe/frappe-bench/sites:cached
`)
	} else if opts.Volumes {
		compose.WriteString(`    volumes:
      - sites-data:/home/frappe/frappe-bench/sites
`)
	}

	compose.WriteString(`    restart: unless-stopped

`)

	// Socketio service
	compose.WriteString(fmt.Sprintf(`  socketio:
    image: %s
    build:
      context: .
      target: socketio
    ports:
      - "%d:9000"
    depends_on:
      - web
    restart: unless-stopped

`, imageTag, opts.SocketPort))

	// Database service
	if opts.IncludeDB {
		if opts.Database == "postgres" {
			compose.WriteString(fmt.Sprintf(`  db:
    image: postgres:15
    ports:
      - "%d:5432"
    environment:
      - POSTGRES_USER=frappe
      - POSTGRES_PASSWORD=frappe
      - POSTGRES_DB=frappe
`, opts.DBPort))
		} else {
			compose.WriteString(fmt.Sprintf(`  db:
    image: mariadb:10.6
    ports:
      - "%d:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=frappe
      - MYSQL_DATABASE=frappe
      - MYSQL_USER=frappe
      - MYSQL_PASSWORD=frappe
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
`, opts.DBPort))
		}

		if opts.Volumes {
			compose.WriteString(`    volumes:
      - db-data:/var/lib/mysql
`)
		}

		compose.WriteString(`    restart: unless-stopped

`)
	}

	// Redis services
	if opts.IncludeRedis {
		compose.WriteString(`  redis-cache:
    image: redis:alpine
    restart: unless-stopped

  redis-queue:
    image: redis:alpine
    restart: unless-stopped

  redis-socketio:
    image: redis:alpine
    restart: unless-stopped

`)
	}

	// Volumes
	if opts.Volumes && opts.Mode == "prod" {
		compose.WriteString(`volumes:
  sites-data:
`)
		if opts.IncludeDB {
			compose.WriteString("  db-data:\n")
		}
	}

	return compose.String()
}

// WriteDockerCompose writes the docker-compose.yml file
func WriteDockerCompose(benchPath string, content string) error {
	path := filepath.Join(benchPath, "docker-compose.yml")
	return os.WriteFile(path, []byte(content), 0644)
}

// DockerComposeUp starts the containers
func DockerComposeUp(benchPath string, detached bool, verbose bool) error {
	args := []string{"compose", "up"}
	if detached {
		args = append(args, "-d")
	}

	cmd := exec.Command("docker", args...)
	cmd.Dir = benchPath
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	cmd.Stdin = os.Stdin

	if verbose {
		fmt.Printf("Running: docker %s\n", strings.Join(args, " "))
	}

	return cmd.Run()
}

// DockerComposeDown stops the containers
func DockerComposeDown(benchPath string, removeVolumes bool, verbose bool) error {
	args := []string{"compose", "down"}
	if removeVolumes {
		args = append(args, "-v")
	}

	cmd := exec.Command("docker", args...)
	cmd.Dir = benchPath
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if verbose {
		fmt.Printf("Running: docker %s\n", strings.Join(args, " "))
	}

	return cmd.Run()
}

// DockerComposeLogs shows container logs
func DockerComposeLogs(benchPath string, service string, follow bool) error {
	args := []string{"compose", "logs"}
	if follow {
		args = append(args, "-f")
	}
	if service != "" {
		args = append(args, service)
	}

	cmd := exec.Command("docker", args...)
	cmd.Dir = benchPath
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	return cmd.Run()
}

// DockerComposePS lists running containers
func DockerComposePS(benchPath string) error {
	cmd := exec.Command("docker", "compose", "ps")
	cmd.Dir = benchPath
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	return cmd.Run()
}
