package container

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// ImageOptions configures container image building
type ImageOptions struct {
	BenchPath  string
	AppName    string   // Primary app name for tagging
	Apps       []string // Apps to include
	Tag        string   // Image tag
	Registry   string   // Registry to push to
	Target     string   // Build target: web, worker, all
	Platform   string   // Target platform(s): linux/amd64,linux/arm64
	FrappeBase string   // Base image from frappe_docker
	Push       bool     // Push after building
	NoCache    bool     // Build without cache
	BuildArgs  map[string]string
	Verbose    bool
}

// DefaultImageOptions returns sensible defaults
func DefaultImageOptions(benchPath string) ImageOptions {
	return ImageOptions{
		BenchPath:  benchPath,
		Target:     "all",
		Platform:   "linux/amd64",
		FrappeBase: "frappe/bench:latest",
		BuildArgs:  make(map[string]string),
	}
}

// GenerateDockerfile creates a multi-stage Dockerfile for the bench
func GenerateDockerfile(opts ImageOptions) string {
	// Determine apps to copy
	appsArg := strings.Join(opts.Apps, " ")

	dockerfile := fmt.Sprintf(`# Generated by weg - Multi-stage Dockerfile for Frappe apps
# Base: %s

ARG FRAPPE_VERSION=15
ARG PYTHON_VERSION=3.11

# =============================================================================
# Stage 1: Builder - Install apps and build assets
# =============================================================================
FROM %s as builder

ARG FRAPPE_VERSION
ARG PYTHON_VERSION

# Set working directory
WORKDIR /home/frappe/frappe-bench

# Copy apps
COPY apps/ apps/

# Install app dependencies
RUN for app in %s; do \
    if [ -d "apps/$app" ]; then \
        echo "Installing $app..." && \
        ./env/bin/pip install -e apps/$app --no-cache-dir; \
    fi; \
done

# Build frontend assets
RUN bench build --production

# =============================================================================
# Stage 2: Production - Minimal runtime image
# =============================================================================
FROM %s as production

ARG FRAPPE_VERSION
ARG PYTHON_VERSION

WORKDIR /home/frappe/frappe-bench

# Copy installed apps from builder
COPY --from=builder /home/frappe/frappe-bench/apps apps/
COPY --from=builder /home/frappe/frappe-bench/sites/assets sites/assets/
COPY --from=builder /home/frappe/frappe-bench/env env/

# Copy sites configuration
COPY sites/ sites/

# Set environment
ENV FRAPPE_BENCH_ROOT=/home/frappe/frappe-bench

# Expose ports
EXPOSE 8000 9000

# Health check
HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD curl -f http://localhost:8000/api/method/ping || exit 1

# Default command
CMD ["bench", "serve", "--port", "8000"]

# =============================================================================
# Stage 3: Web - Gunicorn web server
# =============================================================================
FROM production as web

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "--workers", "4", "--timeout", "120", "frappe.app:application"]

# =============================================================================
# Stage 4: Worker - Background job worker
# =============================================================================
FROM production as worker

CMD ["bench", "worker", "--queue", "default,short,long"]

# =============================================================================
# Stage 5: Scheduler - Job scheduler
# =============================================================================
FROM production as scheduler

CMD ["bench", "schedule"]

# =============================================================================
# Stage 6: Socketio - Real-time communication
# =============================================================================
FROM production as socketio

EXPOSE 9000

CMD ["node", "/home/frappe/frappe-bench/apps/frappe/socketio.js"]
`, opts.FrappeBase, opts.FrappeBase, appsArg, opts.FrappeBase)

	return dockerfile
}

// GenerateDockerignore creates a .dockerignore file
func GenerateDockerignore() string {
	return `# Generated by weg
.git
.gitignore
.weg
*.pyc
__pycache__
*.egg-info
.eggs
dist
build
.venv
venv
env
node_modules
.tox
.pytest_cache
.mypy_cache
*.log
logs
.DS_Store
Thumbs.db
*.swp
*.swo
.idea
.vscode
`
}

// BuildImage builds a container image
func BuildImage(opts ImageOptions) error {
	// Generate Dockerfile if it doesn't exist
	dockerfilePath := filepath.Join(opts.BenchPath, "Dockerfile")
	if _, err := os.Stat(dockerfilePath); os.IsNotExist(err) {
		dockerfile := GenerateDockerfile(opts)
		if err := os.WriteFile(dockerfilePath, []byte(dockerfile), 0644); err != nil {
			return fmt.Errorf("failed to write Dockerfile: %w", err)
		}
	}

	// Generate .dockerignore
	dockerignorePath := filepath.Join(opts.BenchPath, ".dockerignore")
	if _, err := os.Stat(dockerignorePath); os.IsNotExist(err) {
		if err := os.WriteFile(dockerignorePath, []byte(GenerateDockerignore()), 0644); err != nil {
			return fmt.Errorf("failed to write .dockerignore: %w", err)
		}
	}

	// Determine image tag
	tag := opts.Tag
	if tag == "" {
		tag = fmt.Sprintf("%s:latest", opts.AppName)
	}
	if opts.Registry != "" {
		tag = fmt.Sprintf("%s/%s", opts.Registry, tag)
	}

	// Build command
	cmdArgs := []string{"build"}

	// Target
	if opts.Target != "" && opts.Target != "all" {
		cmdArgs = append(cmdArgs, "--target", opts.Target)
	}

	// Platform
	if opts.Platform != "" {
		cmdArgs = append(cmdArgs, "--platform", opts.Platform)
	}

	// Tag
	cmdArgs = append(cmdArgs, "-t", tag)

	// Build args
	for k, v := range opts.BuildArgs {
		cmdArgs = append(cmdArgs, "--build-arg", fmt.Sprintf("%s=%s", k, v))
	}

	// No cache
	if opts.NoCache {
		cmdArgs = append(cmdArgs, "--no-cache")
	}

	// Context
	cmdArgs = append(cmdArgs, ".")

	// Try podman first, then docker
	builder := "docker"
	if _, err := exec.LookPath("podman"); err == nil {
		builder = "podman"
	}

	cmd := exec.Command(builder, cmdArgs...)
	cmd.Dir = opts.BenchPath
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if opts.Verbose {
		fmt.Printf("Running: %s %s\n", builder, strings.Join(cmdArgs, " "))
	}

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("build failed: %w", err)
	}

	// Push if requested
	if opts.Push {
		return PushImage(tag, opts.Verbose)
	}

	return nil
}

// PushImage pushes an image to a registry
func PushImage(tag string, verbose bool) error {
	builder := "docker"
	if _, err := exec.LookPath("podman"); err == nil {
		builder = "podman"
	}

	cmd := exec.Command(builder, "push", tag)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if verbose {
		fmt.Printf("Pushing: %s\n", tag)
	}

	return cmd.Run()
}

// ListImages lists local images matching the app
func ListImages(appName string) ([]string, error) {
	builder := "docker"
	if _, err := exec.LookPath("podman"); err == nil {
		builder = "podman"
	}

	cmd := exec.Command(builder, "images", "--format", "{{.Repository}}:{{.Tag}}", appName)
	output, err := cmd.Output()
	if err != nil {
		return nil, err
	}

	lines := strings.Split(strings.TrimSpace(string(output)), "\n")
	var images []string
	for _, line := range lines {
		if line != "" {
			images = append(images, line)
		}
	}
	return images, nil
}
