package container

import (
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
)

// ImageOptions configures container image building
type ImageOptions struct {
	BenchPath  string
	AppName    string   // Primary app name for tagging
	Apps       []string // Apps to include
	Tag        string   // Image tag
	Registry   string   // Registry to push to
	Target     string   // Build target: web, worker, all
	Platform   string   // Target platform(s): linux/amd64,linux/arm64
	FrappeBase string   // Base image from frappe_docker
	Push       bool     // Push after building
	NoCache    bool     // Build without cache
	BuildArgs  map[string]string
	Verbose    bool
}

// DefaultImageOptions returns sensible defaults
func DefaultImageOptions(benchPath string) ImageOptions {
	return ImageOptions{
		BenchPath:  benchPath,
		Target:     "all",
		Platform:   "linux/amd64",
		FrappeBase: "frappe/bench:latest",
		BuildArgs:  make(map[string]string),
	}
}

// GenerateDockerfile creates a multi-stage Dockerfile for the bench
// Uses Nix/Devbox for system deps, weg structure for the bench
func GenerateDockerfile(opts ImageOptions) string {
	dockerfile := `# Generated by weg - Multi-stage Dockerfile
# Layer 1: Nix for system dependencies (clean, reproducible)
# Layer 2: weg structure with Python/Node deps
# Layer 3: Build assets

ARG DEVBOX_USER=devbox

# =============================================================================
# Stage 1: Nix Base - System dependencies via Devbox
# =============================================================================
FROM jetpackio/devbox:latest AS nix-base

ARG DEVBOX_USER
WORKDIR /app
USER root:root
RUN mkdir -p /app && chown ${DEVBOX_USER}:${DEVBOX_USER} /app
USER ${DEVBOX_USER}:${DEVBOX_USER}

# Copy devbox configuration
COPY --chown=${DEVBOX_USER}:${DEVBOX_USER} devbox.json devbox.lock* ./

# Install system dependencies via Nix
RUN devbox run -- echo "Nix packages installed"

# =============================================================================
# Stage 2: Dependencies - Python & Node packages
# =============================================================================
FROM nix-base AS deps

ARG DEVBOX_USER

# Copy the weg bench structure
COPY --chown=${DEVBOX_USER}:${DEVBOX_USER} apps/ apps/
COPY --chown=${DEVBOX_USER}:${DEVBOX_USER} sites/ sites/
COPY --chown=${DEVBOX_USER}:${DEVBOX_USER} pyproject.toml uv.lock* ./

# Install Python dependencies (editable installs for all apps)
RUN devbox run -- uv sync

# Install Node dependencies for each app
RUN devbox run -- sh -c 'for app in apps/*/; do \
    if [ -f "$app/package.json" ]; then \
        echo "Installing node deps for $app" && \
        (cd "$app" && yarn install --frozen-lockfile); \
    fi; \
done'

# =============================================================================
# Stage 3: Builder - Build frontend assets
# =============================================================================
FROM deps AS builder

# Clean up any existing asset symlinks from local dev (esbuild can't overwrite them)
RUN rm -rf sites/assets/* 2>/dev/null || true && mkdir -p sites/assets

# Build production assets
RUN devbox run -- sh -c ' \
    export FRAPPE_ENV=production && \
    cd apps/frappe && yarn production && cd /app && \
    for app in apps/*/; do \
        appname=$(basename "$app") && \
        if [ -f "$app/package.json" ] && [ "$appname" != "frappe" ]; then \
            echo "Building assets for $appname" && \
            (cd "$app" && yarn production 2>/dev/null) || true; \
        fi; \
    done'

# Create sites/assets structure
RUN devbox run -- sh -c ' \
    mkdir -p sites/assets && \
    for app in apps/*/; do \
        appname=$(basename "$app") && \
        if [ -d "$app/public" ]; then \
            ln -sf "../../apps/$appname/public" "sites/assets/$appname"; \
        fi; \
    done'

# Clean up unnecessary files
RUN find apps -name ".git" -type d -exec rm -rf {} + 2>/dev/null || true && \
    find apps -name "node_modules" -type d -exec rm -rf {} + 2>/dev/null || true && \
    find apps -name "__pycache__" -type d -exec rm -rf {} + 2>/dev/null || true

# =============================================================================
# Stage 4: Production - Minimal runtime image
# =============================================================================
FROM jetpackio/devbox:latest AS production

ARG DEVBOX_USER
WORKDIR /app
USER root:root
RUN mkdir -p /app && chown ${DEVBOX_USER}:${DEVBOX_USER} /app
USER ${DEVBOX_USER}:${DEVBOX_USER}

# Copy devbox config for runtime deps
COPY --chown=${DEVBOX_USER}:${DEVBOX_USER} devbox.json devbox.lock* ./

# Install runtime Nix packages
RUN devbox run -- echo "Runtime packages ready"

# Copy built application from builder
COPY --from=builder --chown=${DEVBOX_USER}:${DEVBOX_USER} /app/apps apps/
COPY --from=builder --chown=${DEVBOX_USER}:${DEVBOX_USER} /app/sites sites/
COPY --from=builder --chown=${DEVBOX_USER}:${DEVBOX_USER} /app/.venv .venv/
COPY --from=builder --chown=${DEVBOX_USER}:${DEVBOX_USER} /app/pyproject.toml ./

# Copy config files if they exist
COPY --chown=${DEVBOX_USER}:${DEVBOX_USER} config/ config/
COPY --chown=${DEVBOX_USER}:${DEVBOX_USER} weg.toml* ./

# Create required directories
RUN mkdir -p logs config/pids

# Environment setup
ENV FRAPPE_ENV=production
ENV PYTHONUNBUFFERED=1

VOLUME ["/app/sites", "/app/logs"]

EXPOSE 8000 9000

HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 \
    CMD curl -f http://localhost:8000/api/method/ping || exit 1

# Default: run gunicorn via devbox
CMD ["devbox", "run", "--", "gunicorn", \
    "--chdir=sites", \
    "--bind=0.0.0.0:8000", \
    "--threads=4", \
    "--workers=2", \
    "--worker-class=gthread", \
    "--worker-tmp-dir=/dev/shm", \
    "--timeout=120", \
    "--preload", \
    "frappe.app:application"]

# =============================================================================
# Stage 5: Web - Gunicorn web server (more workers)
# =============================================================================
FROM production AS web

CMD ["devbox", "run", "--", "gunicorn", \
    "--chdir=sites", \
    "--bind=0.0.0.0:8000", \
    "--threads=4", \
    "--workers=4", \
    "--worker-class=gthread", \
    "--worker-tmp-dir=/dev/shm", \
    "--timeout=120", \
    "--preload", \
    "frappe.app:application"]

# =============================================================================
# Stage 6: Worker - Background job worker
# =============================================================================
FROM production AS worker

CMD ["devbox", "run", "--", "python", "-m", "frappe.utils.background_jobs"]

# =============================================================================
# Stage 7: Scheduler - Job scheduler
# =============================================================================
FROM production AS scheduler

CMD ["devbox", "run", "--", "python", "-m", "frappe.utils.scheduler"]

# =============================================================================
# Stage 8: Socketio - Real-time communication
# =============================================================================
FROM production AS socketio

EXPOSE 9000

CMD ["devbox", "run", "--", "node", "apps/frappe/socketio.js"]
`

	return dockerfile
}

// GenerateDockerignore creates a .dockerignore file
func GenerateDockerignore() string {
	return `# Generated by weg
.git
.gitignore
.weg
*.pyc
__pycache__
*.egg-info
.eggs
dist
build
env
venv
env
node_modules
.tox
.pytest_cache
.mypy_cache
*.log
logs
.DS_Store
Thumbs.db
*.swp
*.swo
.idea
.vscode

# Asset symlinks (rebuilt during container build)
sites/assets

# Local dev files
*.pid
config/pids
.cache
`
}

// BuildImage builds a container image
func BuildImage(opts ImageOptions) error {
	// Generate Dockerfile if it doesn't exist
	dockerfilePath := filepath.Join(opts.BenchPath, "Dockerfile")
	if _, err := os.Stat(dockerfilePath); os.IsNotExist(err) {
		dockerfile := GenerateDockerfile(opts)
		if err := os.WriteFile(dockerfilePath, []byte(dockerfile), 0644); err != nil {
			return fmt.Errorf("failed to write Dockerfile: %w", err)
		}
	}

	// Generate .dockerignore
	dockerignorePath := filepath.Join(opts.BenchPath, ".dockerignore")
	if _, err := os.Stat(dockerignorePath); os.IsNotExist(err) {
		if err := os.WriteFile(dockerignorePath, []byte(GenerateDockerignore()), 0644); err != nil {
			return fmt.Errorf("failed to write .dockerignore: %w", err)
		}
	}

	// Determine image tag
	tag := opts.Tag
	if tag == "" {
		tag = fmt.Sprintf("%s:latest", opts.AppName)
	}
	if opts.Registry != "" {
		tag = fmt.Sprintf("%s/%s", opts.Registry, tag)
	}

	// Build command
	cmdArgs := []string{"build"}

	// Target
	if opts.Target != "" && opts.Target != "all" {
		cmdArgs = append(cmdArgs, "--target", opts.Target)
	}

	// Platform
	if opts.Platform != "" {
		cmdArgs = append(cmdArgs, "--platform", opts.Platform)
	}

	// Tag
	cmdArgs = append(cmdArgs, "-t", tag)

	// Build args
	for k, v := range opts.BuildArgs {
		cmdArgs = append(cmdArgs, "--build-arg", fmt.Sprintf("%s=%s", k, v))
	}

	// No cache
	if opts.NoCache {
		cmdArgs = append(cmdArgs, "--no-cache")
	}

	// Context
	cmdArgs = append(cmdArgs, ".")

	// Try podman first, then docker
	builder := "docker"
	if _, err := exec.LookPath("podman"); err == nil {
		builder = "podman"
	}

	cmd := exec.Command(builder, cmdArgs...)
	cmd.Dir = opts.BenchPath
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if opts.Verbose {
		fmt.Printf("Running: %s %s\n", builder, strings.Join(cmdArgs, " "))
	}

	if err := cmd.Run(); err != nil {
		return fmt.Errorf("build failed: %w", err)
	}

	// Push if requested
	if opts.Push {
		return PushImage(tag, opts.Verbose)
	}

	return nil
}

// PushImage pushes an image to a registry
func PushImage(tag string, verbose bool) error {
	builder := "docker"
	if _, err := exec.LookPath("podman"); err == nil {
		builder = "podman"
	}

	cmd := exec.Command(builder, "push", tag)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr

	if verbose {
		fmt.Printf("Pushing: %s\n", tag)
	}

	return cmd.Run()
}

// ListImages lists local images matching the app
func ListImages(appName string) ([]string, error) {
	builder := "docker"
	if _, err := exec.LookPath("podman"); err == nil {
		builder = "podman"
	}

	cmd := exec.Command(builder, "images", "--format", "{{.Repository}}:{{.Tag}}", appName)
	output, err := cmd.Output()
	if err != nil {
		return nil, err
	}

	lines := strings.Split(strings.TrimSpace(string(output)), "\n")
	var images []string
	for _, line := range lines {
		if line != "" {
			images = append(images, line)
		}
	}
	return images, nil
}
