package services

import (
	"fmt"
	"os"
	"path/filepath"

	"gopkg.in/yaml.v3"
)

// ProcessComposeConfig represents a process-compose.yaml configuration
type ProcessComposeConfig struct {
	Version   string             `yaml:"version,omitempty"`
	Processes map[string]Process `yaml:"processes"`
}

// Process represents a single process in process-compose
type Process struct {
	Command     string            `yaml:"command"`
	WorkingDir  string            `yaml:"working_dir,omitempty"`
	Environment map[string]string `yaml:"environment,omitempty"`
	DependsOn   map[string]DependsOn `yaml:"depends_on,omitempty"`
	Disabled    bool              `yaml:"disabled,omitempty"`
	ReadyProbe  *ReadyProbe       `yaml:"readiness_probe,omitempty"`
}

// DependsOn specifies process dependencies
type DependsOn struct {
	Condition string `yaml:"condition"` // process_started, process_healthy, process_completed_successfully
}

// ReadyProbe defines health check for process readiness
type ReadyProbe struct {
	HTTPGet       *HTTPGet `yaml:"http_get,omitempty"`
	InitialDelay  string   `yaml:"initial_delay_seconds,omitempty"`
	PeriodSeconds int      `yaml:"period_seconds,omitempty"`
}

// HTTPGet defines an HTTP health check
type HTTPGet struct {
	Host   string `yaml:"host,omitempty"`
	Port   int    `yaml:"port"`
	Path   string `yaml:"path,omitempty"`
	Scheme string `yaml:"scheme,omitempty"`
}

// ComposeOptions configures process-compose generation
type ComposeOptions struct {
	BenchPath     string
	WebPort       int
	SocketPort    int
	RedisCache    int
	RedisQueue    int
	IncludeRedis  bool
	IncludeWatch  bool
	FrappeVersion string
	NodePath      string // Path to node binary (for devbox)
}

// DefaultComposeOptions returns sensible defaults
func DefaultComposeOptions(benchPath string) ComposeOptions {
	return ComposeOptions{
		BenchPath:    benchPath,
		WebPort:      8000,
		SocketPort:   9000,
		RedisCache:   13000,
		RedisQueue:   11000,
		IncludeRedis: true,
		IncludeWatch: true,
	}
}

// GenerateProcessCompose creates the process-compose.yaml content
func GenerateProcessCompose(opts ComposeOptions) *ProcessComposeConfig {
	config := &ProcessComposeConfig{
		Version:   "0.5",
		Processes: make(map[string]Process),
	}

	// Redis cache
	if opts.IncludeRedis {
		config.Processes["redis_cache"] = Process{
			Command: fmt.Sprintf("redis-server config/redis_cache.conf"),
		}
		config.Processes["redis_queue"] = Process{
			Command: fmt.Sprintf("redis-server config/redis_queue.conf"),
		}
	}

	// Web server (gunicorn via bench serve)
	config.Processes["web"] = Process{
		Command: fmt.Sprintf("bench serve --port %d", opts.WebPort),
		DependsOn: map[string]DependsOn{
			"redis_cache": {Condition: "process_started"},
			"redis_queue": {Condition: "process_started"},
		},
		ReadyProbe: &ReadyProbe{
			HTTPGet: &HTTPGet{
				Port: opts.WebPort,
				Path: "/api/method/ping",
			},
			InitialDelay:  "5s",
			PeriodSeconds: 5,
		},
	}

	// Socket.io server
	nodePath := opts.NodePath
	if nodePath == "" {
		nodePath = "node"
	}
	config.Processes["socketio"] = Process{
		Command: fmt.Sprintf("%s apps/frappe/socketio.js", nodePath),
		Environment: map[string]string{
			"PORT": fmt.Sprintf("%d", opts.SocketPort),
		},
		DependsOn: map[string]DependsOn{
			"web": {Condition: "process_started"},
		},
	}

	// Background workers
	config.Processes["worker_short"] = Process{
		Command: "bench worker --queue short",
		DependsOn: map[string]DependsOn{
			"redis_queue": {Condition: "process_started"},
		},
	}

	config.Processes["worker_long"] = Process{
		Command: "bench worker --queue long",
		DependsOn: map[string]DependsOn{
			"redis_queue": {Condition: "process_started"},
		},
	}

	config.Processes["worker_default"] = Process{
		Command: "bench worker --queue default",
		DependsOn: map[string]DependsOn{
			"redis_queue": {Condition: "process_started"},
		},
	}

	// Scheduler
	config.Processes["scheduler"] = Process{
		Command: "bench schedule",
		DependsOn: map[string]DependsOn{
			"web": {Condition: "process_started"},
		},
	}

	// Watch mode for development
	if opts.IncludeWatch {
		config.Processes["watch"] = Process{
			Command: "bench watch",
			DependsOn: map[string]DependsOn{
				"web": {Condition: "process_started"},
			},
		}
	}

	return config
}

// WriteProcessCompose writes the process-compose.yaml file
func WriteProcessCompose(benchPath string, config *ProcessComposeConfig) error {
	composePath := filepath.Join(benchPath, "process-compose.yaml")

	data, err := yaml.Marshal(config)
	if err != nil {
		return fmt.Errorf("failed to marshal process-compose config: %w", err)
	}

	// Add header comment
	header := "# Generated by weg - do not edit manually\n# Run 'weg start' to use this configuration\n\n"
	content := header + string(data)

	if err := os.WriteFile(composePath, []byte(content), 0644); err != nil {
		return fmt.Errorf("failed to write process-compose.yaml: %w", err)
	}

	return nil
}

// GenerateAndWrite is a convenience function that generates and writes in one step
func GenerateAndWrite(opts ComposeOptions) error {
	config := GenerateProcessCompose(opts)
	return WriteProcessCompose(opts.BenchPath, config)
}
