package cmd

import (
	"fmt"
	"log"
	"os"
	"os/exec"
	"path/filepath"
	"slices"
	"sync"

	"github.com/gavindsouza/weg/tools"
	"github.com/spf13/cobra"
)

var frappeVersion string

var createCmd = &cobra.Command{
	Use:   "create [bench-name]",
	Short: "Create a new Frappe bench with Devbox",
	Args:  cobra.ExactArgs(1),
	Run: func(cmd *cobra.Command, args []string) {
		benchPath := args[0]
		// cwd, _ := os.Getwd()

		fmt.Printf("🔧 Creating bench at %s with Frappe %s\n", benchPath, frappeVersion)

		os.MkdirAll(benchPath, 0755)
		// create dirs inside the benchPath
		os.MkdirAll(filepath.Join(benchPath, "apps"), 0755)
		os.MkdirAll(filepath.Join(benchPath, "sites"), 0755)
		os.MkdirAll(filepath.Join(benchPath, "config/pids"), 0755)
		os.MkdirAll(filepath.Join(benchPath, "logs"), 0755)

		// git clone the frappe repo
		fmt.Println("🔧 Cloning Frappe repository...")

		// os.Chdir(benchPath)

		// create .envrc
		fmt.Println("🔧 Creating .envrc file...")
		envrcFile, err := os.Create(filepath.Join(benchPath, ".envrc"))
		if err != nil {
			log.Fatalf("Failed to create .envrc file: %v", err)
		}
		defer envrcFile.Close()
		var envrcContent = `# This file is generated by the create command. Do not edit manually.
# Use 'direnv allow' to allow this file.
export VENV_DIR="$(pwd)/env"
export UV_PYTHON=$VENV_DIR/bin/python
export UV_VENV_PATH=$VENV_DIR
export VIRTUAL_ENV=$VENV_DIR
eval "$(devbox generate direnv --print-envrc -e VENV_DIR=$VENV_DIR -e UV_PYTHON=$UV_PYTHON -e UV_VENV_PATH=$UV_VENV_PATH -e VIRTUAL_ENV=$VIRTUAL_ENV)"
`
		os.Setenv("VENV_DIR", fmt.Sprintf("%s/env", benchPath))
		os.Setenv("VIRTUAL_ENV", fmt.Sprintf("%s/env", benchPath))
		os.Setenv("UV_PYTHON", fmt.Sprintf("%s/bin/python", os.Getenv("VENV_DIR")))
		os.Setenv("UV_VENV_PATH", os.Getenv("VENV_DIR"))

		// envrcContent := fmt.Sprintf("export PATH=$PATH:%s/.devbox/bin", benchPath)
		if _, err := envrcFile.WriteString(envrcContent); err != nil {
			log.Fatalf("Failed to write to .envrc file: %v", err)
		}

		fmt.Println("📦 Initializing Devbox...")
		runCmd("devbox", benchPath, "init")

		ORIGINAL_PATH := os.Getenv("PATH")
		os.Setenv("PATH", fmt.Sprintf("%s/.devbox/bin:%s/.devbox/nix/profile/default/bin:%s", benchPath, benchPath, ORIGINAL_PATH))

		fmt.Println("📦 Setting up Frappe Dependencies...")

		var packages, _ = tools.GetDependencies(frappeVersion)
		var devboxArgs []string = []string{"uv"}

		for _, pkg := range packages {
			if pkg.Version != "" {
				devboxArgs = append(devboxArgs, fmt.Sprintf("%s@%s", pkg.Name, pkg.Version))
			} else {
				devboxArgs = append(devboxArgs, pkg.Name)
			}
		}

		runCmd("devbox", benchPath, append([]string{"add"}, devboxArgs...)...)

		// get all apps using git clone in parallel
		fmt.Println("🔧 Cloning Frappe apps...")

		var apps = []tools.FrappeApp{
			{Url: "https://github.com/frappe/frappe.git", Name: "frappe", Branch: "develop"},
			{Url: "https://github.com/frappe/erpnext.git", Name: "erpnext", Branch: "develop"},
			{Url: "https://github.com/frappe/hrms.git", Name: "hrms", Branch: "develop"},
			{Url: "https://github.com/The-Commit-Company/Raven.git", Name: "raven", Branch: "develop"},
		}

		tools.CloneRepos(apps, filepath.Join(benchPath, "apps"))

		runCmd("devbox", benchPath, "shell")

		// create a pyproject.toml file for the bench
		fmt.Println("🔧 Creating pyproject.toml file...")
		pyprojectFile, err := os.Create(filepath.Join(benchPath, "pyproject.toml"))
		if err != nil {
			log.Fatalf("Failed to create pyproject.toml file: %v", err)
		}
		defer pyprojectFile.Close()
		var pyprojectContent = fmt.Sprintf(`# This file is generated by the create command. Do not edit manually.
# Use 'devbox add' to add dependencies.
[project]
name = "frappe-bench"
version = "0.1.0"
requires-python = ">=%s"
`, packages[slices.IndexFunc(packages, func(pkg tools.Dependency) bool {
			return pkg.Name == "python"
		})].Version)
		if _, err := pyprojectFile.WriteString(pyprojectContent); err != nil {
			log.Fatalf("Failed to write to pyproject.toml file: %v", err)
		}

		runCmd("direnv", benchPath, "allow")

		runCmd("uv", benchPath, "venv", "env", "--python", benchPath+"/.devbox/nix/profile/default/bin/python")

		// write apps.txt file in sites
		appsFile, err := os.Create(filepath.Join(benchPath, "sites/apps.txt"))
		if err != nil {
			log.Fatalf("Failed to create apps.txt file: %v", err)
		}
		defer appsFile.Close()
		for _, app := range apps {
			if _, err := appsFile.WriteString(app.Name + "\n"); err != nil {
				log.Fatalf("Failed to write to apps.txt file: %v", err)
			}
		}

		// setup requirements js & python, we can do this in parallel
		var wg sync.WaitGroup

		var appArgs []string

		for _, app := range apps {
			appDir := filepath.Join(benchPath, "apps", app.Name)
			appArgs = append(appArgs, appDir)
		}

		// Combine fixed args with dynamic ones
		uvArgs := append([]string{"add", "--active", "--editable"}, appArgs...)

		// Run uv command asynchronously
		runCmdAsync(&wg, "uv", benchPath, uvArgs...)

		// Run yarn install for each app asynchronously
		for _, app := range apps {
			runCmdAsync(&wg, "yarn", filepath.Join(benchPath, "apps", app.Name), "install")
		}

		// Wait for all async commands to complete
		wg.Wait()

		// Run other commands synchronously if needed
		runCmd("bench", benchPath, "setup", "config")
		runCmd("bench", benchPath, "setup", "redis")
		runCmd("bench", benchPath, "setup", "procfile")

		// fmt.Println("🔧 Creating .envrc file... done")

	},
}

func init() {
	rootCmd.AddCommand(createCmd)
	createCmd.Flags().StringVar(&frappeVersion, "frappe-version", "develop", "Frappe version to use")
}

func runCmd(binary, dir string, args ...string) {
	cmd := exec.Command(binary, args...)
	cmd.Dir = dir
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	if err := cmd.Run(); err != nil {
		log.Fatalf("Command failed (%s): %s %v\n%v", dir, binary, args, err)
	}
}

func runCmdAsync(wg *sync.WaitGroup, binary, dir string, args ...string) {
	wg.Add(1)
	go func() {
		defer wg.Done()
		runCmd(binary, dir, args...)
	}()
}
