package cmd

import (
	"fmt"
	"os"
	"path/filepath"
)

// initDevboxEnvironment sets up devbox, direnv, and uv in the .weg directory
func initDevboxEnvironment(wegPath, version string) error {
	// Create .envrc - use .venv which devbox's python plugin creates automatically
	envrc := `# Generated by weg. Do not edit manually.
eval "$(devbox generate direnv --print-envrc)"
`
	if err := os.WriteFile(filepath.Join(wegPath, ".envrc"), []byte(envrc), 0644); err != nil {
		return fmt.Errorf("failed to create .envrc: %w", err)
	}

	// Initialize devbox
	PrintVerbose("Initializing devbox...")
	if err := runCmdInDir(wegPath, "devbox", "init"); err != nil {
		return fmt.Errorf("devbox init failed: %w", err)
	}

	// Add required packages via devbox
	PrintVerbose("Installing dependencies via devbox...")
	packages := getDevboxPackages(version)
	args := append([]string{"add"}, packages...)
	if err := runCmdInDir(wegPath, "devbox", args...); err != nil {
		return fmt.Errorf("devbox add failed: %w", err)
	}

	// Allow direnv
	PrintVerbose("Allowing direnv...")
	if err := runCmdInDir(wegPath, "direnv", "allow"); err != nil {
		// Don't fail on direnv error - might not be installed
		PrintVerbose("direnv not available: %v", err)
	}

	// Create pyproject.toml for uv
	pyproject := fmt.Sprintf(`[project]
name = "frappe-bench"
version = "0.1.0"
requires-python = ">=3.11"
`)
	if err := os.WriteFile(filepath.Join(wegPath, "pyproject.toml"), []byte(pyproject), 0644); err != nil {
		return fmt.Errorf("failed to create pyproject.toml: %w", err)
	}

	// Note: devbox's python plugin automatically creates .venv
	// No need to create a separate venv

	return nil
}

// getDevboxPackages returns the devbox packages for a Frappe version
func getDevboxPackages(version string) []string {
	// Base packages
	packages := []string{
		"uv",
		"python@3.11",
		"nodejs@18",
		"yarn",
		"mariadb@10.11",
		"redis@7",
		"process-compose",
	}

	// Add version-specific packages
	switch version {
	case "16":
		packages = append(packages, "python@3.12")
	case "14":
		packages = append(packages, "python@3.10")
	}

	return packages
}
