package cmd

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
)

// initDevboxEnvironment sets up devbox, direnv, and uv in the .weg directory
func initDevboxEnvironment(wegPath, version string) error {
	// Create .envrc - use .venv which devbox's python plugin creates automatically
	envrc := `# Generated by weg. Do not edit manually.
eval "$(devbox generate direnv --print-envrc)"
`
	if err := os.WriteFile(filepath.Join(wegPath, ".envrc"), []byte(envrc), 0644); err != nil {
		return fmt.Errorf("failed to create .envrc: %w", err)
	}

	// Write service configs BEFORE devbox init/add
	// devbox won't overwrite existing files in devbox.d/
	PrintVerbose("Writing service configurations...")
	if err := writeServiceConfigs(wegPath); err != nil {
		return fmt.Errorf("failed to write service configs: %w", err)
	}

	// Write devbox.json directly with socket-only configuration
	PrintVerbose("Creating devbox.json...")
	if err := writeDevboxJSON(wegPath, version); err != nil {
		return fmt.Errorf("failed to create devbox.json: %w", err)
	}

	// Install devbox packages (this will use our pre-written configs)
	PrintVerbose("Installing dependencies via devbox...")
	if err := runCmdInDir(wegPath, "devbox", "install"); err != nil {
		return fmt.Errorf("devbox install failed: %w", err)
	}

	// Allow direnv
	PrintVerbose("Allowing direnv...")
	if err := runCmdInDir(wegPath, "direnv", "allow"); err != nil {
		// Don't fail on direnv error - might not be installed
		PrintVerbose("direnv not available: %v", err)
	}

	// Create pyproject.toml for uv
	pyproject := `[project]
name = "frappe-bench"
version = "0.1.0"
requires-python = ">=3.11"
`
	if err := os.WriteFile(filepath.Join(wegPath, "pyproject.toml"), []byte(pyproject), 0644); err != nil {
		return fmt.Errorf("failed to create pyproject.toml: %w", err)
	}

	// Note: devbox's python plugin automatically creates .venv
	// No need to create a separate venv

	return nil
}

// writeServiceConfigs creates devbox.d/ configs for socket-only operation
// These must be written BEFORE devbox install, as devbox won't overwrite existing files
func writeServiceConfigs(wegPath string) error {
	// Ensure we have an absolute path for socket locations
	absWegPath, err := filepath.Abs(wegPath)
	if err != nil {
		return fmt.Errorf("failed to get absolute path: %w", err)
	}

	// Create devbox.d/mariadb directory
	mariadbDir := filepath.Join(wegPath, "devbox.d", "mariadb")
	if err := os.MkdirAll(mariadbDir, 0755); err != nil {
		return fmt.Errorf("failed to create mariadb config dir: %w", err)
	}

	// MariaDB config - disable TCP networking, use socket only
	// This prevents port conflicts with system mariadb on port 3306
	myCnf := `# Generated by weg - socket-only configuration
# This prevents port conflicts with system mariadb

[mariadbd]
skip-networking
log_error = mysql.log
`
	if err := os.WriteFile(filepath.Join(mariadbDir, "my.cnf"), []byte(myCnf), 0644); err != nil {
		return fmt.Errorf("failed to write my.cnf: %w", err)
	}

	// Create devbox.d/redis directory and virtenv/redis for socket
	redisDir := filepath.Join(wegPath, "devbox.d", "redis")
	if err := os.MkdirAll(redisDir, 0755); err != nil {
		return fmt.Errorf("failed to create redis config dir: %w", err)
	}

	// Create virtenv/redis directory for the socket file
	redisVirtenv := filepath.Join(wegPath, ".devbox", "virtenv", "redis")
	if err := os.MkdirAll(redisVirtenv, 0755); err != nil {
		return fmt.Errorf("failed to create redis virtenv dir: %w", err)
	}

	// Redis config - disable TCP, use socket only
	// This prevents port conflicts with system redis on port 6379
	// Use absolute path for socket since redis-server working dir is unpredictable
	redisSocketPath := filepath.Join(absWegPath, ".devbox", "virtenv", "redis", "redis.sock")
	redisConf := fmt.Sprintf(`# Generated by weg - socket-only configuration
# This prevents port conflicts with system redis

# Disable TCP listening (port 0 = disabled)
port 0

# Enable Unix socket with absolute path
unixsocket %s
unixsocketperm 770
`, redisSocketPath)

	if err := os.WriteFile(filepath.Join(redisDir, "redis.conf"), []byte(redisConf), 0644); err != nil {
		return fmt.Errorf("failed to write redis.conf: %w", err)
	}

	return nil
}

// writeDevboxJSON creates devbox.json with packages and socket-only env vars
func writeDevboxJSON(wegPath, version string) error {
	packages := getDevboxPackages(version)

	// Build devbox.json structure
	config := map[string]any{
		"$schema":  "https://raw.githubusercontent.com/jetify-com/devbox/main/.schema/devbox.schema.json",
		"packages": packages,
		"env": map[string]string{
			// Disable Redis TCP port - forces socket-only operation
			// The redis process-compose uses: redis-server $REDIS_CONF --port $REDIS_PORT
			"REDIS_PORT": "0",
		},
		"shell": map[string]any{
			"init_hook": []string{
				"echo 'Weg environment ready' > /dev/null",
			},
		},
	}

	data, err := json.MarshalIndent(config, "", "  ")
	if err != nil {
		return fmt.Errorf("failed to marshal devbox.json: %w", err)
	}

	if err := os.WriteFile(filepath.Join(wegPath, "devbox.json"), data, 0644); err != nil {
		return fmt.Errorf("failed to write devbox.json: %w", err)
	}

	return nil
}

// getDevboxPackages returns the devbox packages for a Frappe version
func getDevboxPackages(version string) []string {
	// Base packages
	packages := []string{
		"uv",
		"python@3.11",
		"nodejs@18",
		"yarn",
		"mariadb@10.11",
		"redis@7",
		"process-compose",
	}

	// Add version-specific packages
	switch version {
	case "16":
		packages = append(packages, "python@3.12")
	case "14":
		packages = append(packages, "python@3.10")
	}

	return packages
}
